/**
  Count from 10 -1 using for loop 

  Count down from 100 - 0 decreasing number by 10 each time

 */
 for (Integer count = 10; count > 0; --count){
    System.debug(count);
 }

System.debug('----------------'); 

 for (Integer count = 100; count >= 0; count -=10){
    System.debug(count);
 }

 System.debug('----------------'); 

 for (Integer count = 1000; count >= 0; count -=100){
    System.debug(count);
 }

 